### ISSUE TITLE
About proteins embedding

### ISSUE THREAD

**Issue by viko-3** [tbepler/prose#2]
Thanks for your great work! Because of the length of time, I read it roughly.
As your paper write: Our encoder consists of 3 biLSTM layers with 512 hidden units each and a ﬁnal output embedding dimension of 100.
![image](https://user-images.githubusercontent.com/55910336/133113086-b3b54f4d-0cc6-4aaf-b132-abc49a90af7e.png)

As your test code about pretrain model:

> python embed_sequences.py --pool avg -o data/demo.h5 data/demo.fa

the output dimension is  6165.
If I only want to get the embedding result(dimension of 100).How I get it?
And what is the 6165 means?

**Comment by tbepler** [comment]
The models provided here work a bit differently than our original ICLR 2019 model. It's 3 biLSTM layers but with 1024 hidden units each and skip connections to the last layer.

![image](https://user-images.githubusercontent.com/5326126/133189232-a76adb52-e4cd-4cf1-8cec-fe4bc02da168.png)

There is still a 100-d vector embedding, but, by default, we provide the stack of LSTM representations concatenated with the one-hot embeddings of the input (6*1024 + 21 = 6165) as the embedding, because we found this worked better for transfer learning. 

If you want just the 100-d vector embedding, change `model.transform(x)` to just `model(x)` [here](https://github.com/tbepler/prose/blob/3416cc8455438d154251cc57cd123e5e17807a7b/embed_sequences.py#L30).

**Comment by viko-3** [comment]
> The models provided here work a bit differently than our original ICLR 2019 model. It's 3 biLSTM layers but with 1024 hidden units each and skip connections to the last layer.
> 
> ![image](https://user-images.githubusercontent.com/5326126/133189232-a76adb52-e4cd-4cf1-8cec-fe4bc02da168.png)
> 
> There is still a 100-d vector embedding, but, by default, we provide the stack of LSTM representations concatenated with the one-hot embeddings of the input (6*1024 + 21 = 6165) as the embedding, because we found this worked better for transfer learning.
> 
> If you want just the 100-d vector embedding, change `model.transform(x)` to just `model(x)` [here](https://github.com/tbepler/prose/blob/3416cc8455438d154251cc57cd123e5e17807a7b/embed_sequences.py#L30).

ok Thanks for your reply.
I will continue to study it.

**Comment by viko-3** [comment]
> The models provided here work a bit differently than our original ICLR 2019 model. It's 3 biLSTM layers but with 1024 hidden units each and skip connections to the last layer.
> 
> ![image](https://user-images.githubusercontent.com/5326126/133189232-a76adb52-e4cd-4cf1-8cec-fe4bc02da168.png)
> 
> There is still a 100-d vector embedding, but, by default, we provide the stack of LSTM representations concatenated with the one-hot embeddings of the input (6*1024 + 21 = 6165) as the embedding, because we found this worked better for transfer learning.
> 
> If you want just the 100-d vector embedding, change `model.transform(x)` to just `model(x)` [here](https://github.com/tbepler/prose/blob/3416cc8455438d154251cc57cd123e5e17807a7b/embed_sequences.py#L30).

Can I ask one more question, does 21 stand for 21 protein domains?

**Comment by tbepler** [comment]
20 canonical amino acids + 1 for unknown ('X').

**Comment by viko-3** [comment]
> 20 canonical amino acids + 1 for unknown ('X').

I'm so grateful for the insight!Thank you
