### ISSUE TITLE
Stucture similarity confusion 

### ISSUE THREAD

**Issue by edikedik** [tbepler/prose#4]
Hello, sir!

I'm trying to use embeddings for distance calculation between protein sequences. In both papers (2019, 2021), you proposed the "soft sequence alignment" method. 

I have several questions regarding the SSA:

1. In the recent paper (2021), the size of the embeddings was reduced via linear projection from ~6K to 100. Here, by default, the model outputs full embeddings. Do you think the SSA would apply to these "full" embeddings? I noticed that in the `SkipLSTM` encoder, there is a `proj` attribute which I assume relates to the linear projection matrix. Can I apply this layer to the embeddings to get the same representation as the one used in the paper for distance calculation?
2. Implementing the SSA, I stumbled upon ambiguity. Namely, the formula for calculation of the alpha and beta (`a_ij` and `b_ij`) parameters have the normalization summed over `n` and `m` sequence elements, respectively (`sum_l^n (k_il)`, `sum_l^m (k_lj)`). However, `i` and `j` are indices reserved for the elements of the first and the second sequences, resp. For instance, in the first sum (`sum_l^n (k_il)`), we fix the `i` and sum over each `l`-th element of the second sequence, `m` in total (and not `n`). Summing up, could you please clarify how to correctly calculate the normalization constant in the "alpha" and "beta" parameters.
3. In the paper, you used full protein sequences from UniProt. In my case, I use partial (domain) subsequences and calculate the distance between them. Do you think such distance would still be meaningful?

I realize that's a lot of abstract questions, so any insight you could give is highly appreciated!

Ivan

**Comment by tbepler** [comment]
In answer to your questions:

1.  Yes, we output the "full" embeddings by default, because we found they were more effective as features for downstream tasks than the reduced 100-d embeddings. Two possible options here are: 1) you can get the 100-d embeddings by changing https://github.com/tbepler/prose/blob/3416cc8455438d154251cc57cd123e5e17807a7b/embed_sequences.py#L30 (in the embed_sequences.py script) to use `model(x)` instead of `model.transform(x)`. 2) you can use the "full" embeddings in the SSA, actually I've found they work nicely, but they work better if you use the dot product or cosine similarity instead of the Manhattan/Euclidean distance between the embeddings in the SSA calculation.
2. It sounds like this is a typo in the paper. I'll have to double check, but you can reference the implementation [here](https://github.com/tbepler/prose/blob/3416cc8455438d154251cc57cd123e5e17807a7b/prose/models/multitask.py#L179) to see for certain.
3. Definitely! It works well on domains in my experience.

Hope that helps!

**Comment by edikedik** [comment]
Thank you kindly!
